version: '3'
services:
  web:
    build: ./docker/nginx
    container_name: refrigeram_api
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.5
    restart: always
    container_name: refrigeram_api_db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    container_name: refrigeram_api_php
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  schemaspy-nginx:
    image: nginx:1.13.9-alpine
    container_name: refrigeram_api_schemaspy_nginx
    volumes:
      - ./docker/schemaspy/output:/var/www/html:ro
      - ./docker/schemaspy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8082:80'
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  schemaspy:
    build: ./docker/schemaspy
    image: treetips/schemaspy-mysql
    volumes:
      - ./docker/schemaspy/output:/app/html:rw
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja.JP.UTF-8
      - TZ=Asia/Tokyo
    container_name: refrigeram_api_schemaspy_local
    command: 'java -jar schemaspy.jar'
    working_dir: '/app'
    links:
      - db

  redoc:
    image: redocly/redoc
    container_name: refrigeram_api_redoc
    ports:
      - 8004:80
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      PAGE_TITLE: baby_diary api
      SPEC_URL: openapi.yml

  api-mock:
    image: stoplight/prism
    container_name: refrigeram_api_mock
    ports:
      - 4011:4010
    command: mock -h 0.0.0.0 -d /app/openapi.yml
    volumes:
      - ./openapi.yml:/app/openapi.yml
